In [9]:
import numpy as np
import pandas as pd
import math as math

def price_option(optiontype, s0,k,r,u,d,n, deltat) : 
    s = np.zeros(shape=(n,n))
    c = np.zeros(shape=(n,n))
    s= pd.DataFrame(s) 
    c= pd.DataFrame(c) 
    q=0.5695   #should be changed to the formula 
    s[0][0] = s0 
    c[0][0] = s0-k
    if optiontype == 'put' :  
        for i in range(0,n-1) : 
            j=0
            for j in range(0,i+1) :   
                s[i+1][j]= u*s[i][j] 
                s[i+1][j+1] = d*s[i][j]
                if k-(u*s[i][j]) >= 0 :
                    c[i+1][j] = k-(u*s[i][j])
                else : 
                    c[i+1][j] = 0 
                if k-(d*s[i][j]) >= 0 :
                    c[i+1][j+1] = k-(d*s[i][j])
                else: 
                    c[i+1][j+1] = 0
                    
    elif optiontype == 'call' : 
        
        for i in range(0,n-1) : 
            j=0
            for j in range(0,i+1) :   
                s[i+1][j]= u*s[i][j] 
                s[i+1][j+1] = d*s[i][j]
                if (u*s[i][j])-k >= 0 :
                    c[i+1][j] = (u*s[i][j])-k
                else : 
                    c[i+1][j] = 0 
                if (d*s[i][j])-k >= 0 :
                    c[i+1][j+1] = (d*s[i][j])-k
                else: 
                    c[i+1][j+1] = 0
    else: print('please put call or put as optiontype')
        
    x = n
    for i in range(0,n-1) :
        for j in range(0,x-1) : 
            c[n-2-i][j]= (c[n-1-i][j]*q + c[n-1-i][j+1]*(1-q))*math.exp(-r*deltat)
        x -=1
                    
    print('Option price =', c[0][0])
    return(c.head(20))

In [ ]:
price_option('put', 100,105,0.079,1.1,0.9,100,0.083333)

In [11]:
price_option('put', 111, 96 , 0.05, 1.03,0.97,10, (0.08333) )

Option price = 0.06918342620585144

,0,1,2,3,4,5,6,7,8,9
0,0.069183,0.017586,0.002268,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.138112,0.038020,0.005290,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.271862,0.081687,0.012339,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.526078,0.174218,0.028781,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.996648,0.368303,0.067134,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,1.837541,0.770285,0.156595,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.267213,1.589595,0.365270,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.518187,3.224647,0.852021
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.605785,6.394622
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.614352